version: "4"

services:
    mysql:
        image: mysql:8.3.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    redis:
        image: redis:7.2.4
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
    
    zookeeper:
        image: "bitnami/zookeeper:3.8-debian-10"
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        restart: always
        
    kafka:
        image: "bitnami/kafka:3.1-debian-10"
        ports:
            - "9092:9092"
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
        restart: always